server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    activate:
      on-profile: prod
  devtools:
    livereload:
      # livereload 서버 켜기
      enabled: true
  servlet:
    multipart:
      max-file-size: 50MB

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@db202201212242_high?TNS_ADMIN=/usr/local/key/Wallet_DB202201212242
    username: blog
    password: 1
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update  #create/update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    #show-sql: true
    properties:
      hibernate.format_sql: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  
# Kakao-API Dev
kakao:
  client-id: 5e74706108bffe6ea2bef14ddb178495
  redirect-uri: http://140.238.11.178/auth/kakao/callback
  logout-uri: http://140.238.11.178/auth/kakao/logout
  login-uri: https://kauth.kakao.com/oauth/authorize?client_id=%s&redirect_uri=%s&response_type=code
  token-req-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me
  login-key: jsblog  

  #redirect-uri: http://140.238.11.178/auth/kakao/callback
  #logout-uri: http://140.238.11.178/auth/kakao/logout
  

# Riot-Api
riot:
  api:
    #{summonerName} #SUMMONER-V4 -> id, name, summonerLevel
    summoner-url: https://kr.api.riotgames.com/lol/summoner/v4/summoners/by-name/{text}
    #{encryptedSummonerId} #LEAGUE-V4 -> tier, rank, league points, wins, losses
    league-etnry-url: https://kr.api.riotgames.com/lol/league/v4/entries/by-summoner/{text} 
    #{puuid} #MATCH-V5
    match-by-puuid-url : https://asia.api.riotgames.com/lol/match/v5/matches/by-puuid/{text}/ids?start=0&count=5
    #{matchId} #MATCH-V5
    match-by-MatchId-url : https://asia.api.riotgames.com/lol/match/v5/matches/{text}
    key: RGAPI-83eba5b5-621c-401c-9ab0-061ea6cb35e7
  



  